### ISSUE TITLE
jigna tests fail on Mac OS X 10.10 with Canopy 32bit on Python 2.7.6

### ISSUE THREAD

**Issue by alexlib** [enthought/jigna#45]
nosetests create the following errors

EEEE
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'Signal')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/alex/Downloads/jigna/jigna/jigna/tests/test_html_widget.py", line 1, in <module>
    from jigna.api import HTMLWidget, Template
  File "/Users/alex/Downloads/jigna/jigna/jigna/api.py", line 3, in <module>
    from html_widget import HTMLWidget
  File "/Users/alex/Downloads/jigna/jigna/jigna/html_widget.py", line 16, in <module>
    from .qt_server import QtServer
  File "/Users/alex/Downloads/jigna/jigna/jigna/qt_server.py", line 20, in <module>
    from jigna.core.proxy_qwebview import ProxyQWebView
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/proxy_qwebview.py", line 14, in <module>
    from jigna.core.network_access import ProxyAccessManager
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 129, in <module>
    class ProxyReplyWorker(QtCore.QThread):
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 133, in ProxyReplyWorker
    metaDataChanged = QtCore.Signal()
AttributeError: 'module' object has no attribute 'Signal'

======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'Signal')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/alex/Downloads/jigna/jigna/jigna/tests/test_jigna_qt.py", line 2, in <module>
    from jigna.api import HTMLWidget, Template
  File "/Users/alex/Downloads/jigna/jigna/jigna/api.py", line 3, in <module>
    from html_widget import HTMLWidget
  File "/Users/alex/Downloads/jigna/jigna/jigna/html_widget.py", line 16, in <module>
    from .qt_server import QtServer
  File "/Users/alex/Downloads/jigna/jigna/jigna/qt_server.py", line 20, in <module>
    from jigna.core.proxy_qwebview import ProxyQWebView
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/proxy_qwebview.py", line 14, in <module>
    from jigna.core.network_access import ProxyAccessManager
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 129, in <module>
    class ProxyReplyWorker(QtCore.QThread):
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 133, in ProxyReplyWorker
    metaDataChanged = QtCore.Signal()
AttributeError: 'module' object has no attribute 'Signal'

======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'Signal')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/alex/Downloads/jigna/jigna/jigna/tests/test_jigna_web.py", line 13, in <module>
    from jigna.api import Template, WebApp
  File "/Users/alex/Downloads/jigna/jigna/jigna/api.py", line 3, in <module>
    from html_widget import HTMLWidget
  File "/Users/alex/Downloads/jigna/jigna/jigna/html_widget.py", line 16, in <module>
    from .qt_server import QtServer
  File "/Users/alex/Downloads/jigna/jigna/jigna/qt_server.py", line 20, in <module>
    from jigna.core.proxy_qwebview import ProxyQWebView
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/proxy_qwebview.py", line 14, in <module>
    from jigna.core.network_access import ProxyAccessManager
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 129, in <module>
    class ProxyReplyWorker(QtCore.QThread):
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 133, in ProxyReplyWorker
    metaDataChanged = QtCore.Signal()
AttributeError: 'module' object has no attribute 'Signal'

======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'Signal')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/alex/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/alex/Downloads/jigna/jigna/jigna/tests/test_jigna_web_async.py", line 5, in <module>
    from test_jigna_web import TestJignaWebSync, Person
  File "/Users/alex/Downloads/jigna/jigna/jigna/tests/test_jigna_web.py", line 13, in <module>
    from jigna.api import Template, WebApp
  File "/Users/alex/Downloads/jigna/jigna/jigna/api.py", line 3, in <module>
    from html_widget import HTMLWidget
  File "/Users/alex/Downloads/jigna/jigna/jigna/html_widget.py", line 16, in <module>
    from .qt_server import QtServer
  File "/Users/alex/Downloads/jigna/jigna/jigna/qt_server.py", line 20, in <module>
    from jigna.core.proxy_qwebview import ProxyQWebView
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/proxy_qwebview.py", line 14, in <module>
    from jigna.core.network_access import ProxyAccessManager
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 129, in <module>
    class ProxyReplyWorker(QtCore.QThread):
  File "/Users/alex/Downloads/jigna/jigna/jigna/core/network_access.py", line 133, in ProxyReplyWorker
    metaDataChanged = QtCore.Signal()
AttributeError: 'module' object has no attribute 'Signal'

----------------------------------------------------------------------
Ran 4 tests in 0.310s

FAILED (errors=4)

**Comment by pankajp** [comment]
@agrawalprash This is probably when using PyQt4 , caused by https://github.com/enthought/jigna/pull/41
Jigna's pyside/pyqt compat code in https://github.com/enthought/jigna/blob/master/jigna/qt.py does not take care to handle their differences.
It should be modified to add the `sip.setapi` calls ( https://github.com/enthought/pyface/blob/master/pyface/qt/__init__.py ) and the property/signal/slot aliases ( https://github.com/enthought/pyface/blob/master/pyface/qt/QtCore.py ) at the least.

**Comment by csirac2** [comment]
A similar error occurs using Debian jessie's packaged python-qt4/traits and friends. Works from a virtualenv.

```
$ python examples/simple_view.py 
Traceback (most recent call last):
  File "examples/simple_view.py", line 7, in <module>
    from jigna.api import HTMLWidget, Template
  File "/usr/local/src/github.com/enthought/jigna/jigna/api.py", line 3, in <module>
    from html_widget import HTMLWidget
  File "/usr/local/src/github.com/enthought/jigna/jigna/html_widget.py", line 18, in <module>
    from .qt_server import QtServer
  File "/usr/local/src/github.com/enthought/jigna/jigna/qt_server.py", line 20, in <module>
    from jigna.core.proxy_qwebview import ProxyQWebView
  File "/usr/local/src/github.com/enthought/jigna/jigna/core/proxy_qwebview.py", line 15, in <module>
    from jigna.core.network_access import ProxyAccessManager
  File "/usr/local/src/github.com/enthought/jigna/jigna/core/network_access.py", line 130, in <module>
    class ProxyReplyWorker(QtCore.QThread):
  File "/usr/local/src/github.com/enthought/jigna/jigna/core/network_access.py", line 134, in ProxyReplyWorker
    metaDataChanged = QtCore.Signal()
AttributeError: 'module' object has no attribute 'Signal'
```
